# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always


  employeeregistration:
    container_name: emp_registration
    build:
      context: .
      dockerfile: /home/knoldus/Downloads/EmployeeBenefit/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo